import Head from 'next/head';
import Image from 'next/image';

import Avatar from '../components/Avatar';
import { MicrophoneIcon, ViewGridIcon } from '@heroicons/react/solid';
import { SearchIcon } from '@heroicons/react/outline';
import Footer from '../components/Footer';
import { useRef } from 'react';
import { useRouter } from 'next/router';

export default function Home() {
  const searchRef = useRef(null);
  const router = useRouter();

  const googleSearch = (e) => {
    e.preventDefault();
    const term = searchRef.current.value;
    if (!term) {
      return;
    }
    console.log(term);
    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col items-center justifycenter h-screen">
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/** Right */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/** Left */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          <ViewGridIcon className="h-10 w-10 p-2  rounded-full hover:bg-gray-100 cursor-pointer" />
          <Avatar url="https://media-exp1.licdn.com/dms/image/C5603AQHAefh8BpMHTg/profile-displayphoto-shrink_400_400/0/1615776794797?e=1628121600&v=beta&t=uGeRAMJChoIIaegA-g7uj07Tdmg68wlLJA4nxDwtZbQ" />
        </div>
      </header>
      {/** Body */}
      <form className="flex flex-col items-center mt-40 flex-grow w-4/5">
        <Image
          src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
        />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500 " />
          <input
            type="text"
            className="flex-grow focus:outline-none"
            ref={searchRef}
          />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/3 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button className="btn" onClick={googleSearch}>
            Google Search
          </button>
          <button className="btn" onClick={googleSearch}>
            I'm Feeling Lucky
          </button>
        </div>
      </form>
      {/** Footer */}
      <Footer />
    </div>
  );
}
